### ISSUE TITLE
Access libs in C# console App

### ISSUE THREAD

**Issue by Blubberblub** [FactEngineCommunity/KuzuDB-DotNetInterface#2]
Hey everyone,

I'm trying to add the generated DLLs to a basic C# console app as an example for the repo. However i didn't have success with it so far. 
I tried:
- adding the KuzuDB-Net project as a Reference in Visual Studio (like the VB example does)
- adding the generated DLLs as reference
- Adding the wrapper files, the kuzunet.dll and the

Code for the sample App:

```cs
using System;
using static kuzunet;

namespace ConsoleAppExample
{
    internal class Program
    {
        static void Main(string[] args)
        {
            kuzu_database db = kuzu_database_init("test", kuzu_default_system_config());
            kuzu_connection conn = kuzu_connection_init(db);

            kuzu_query_result result = kuzu_connection_query(conn, "CREATE NODE TABLE User(name STRING, age INT64, PRIMARY KEY (name))");
            kuzu_query_result_destroy(result);

            kuzu_connection_destroy(conn);
            kuzu_database_destroy(db);

            Console.WriteLine("Press enter to close...");
            Console.ReadLine();
        }
        
    }
}

```

I'm getting all the type hints and so on, but when testing i get different exceptions:
```
TypeInitializationException: The type initializer for 'kuzunetPINVOKE' threw an exception.
TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
```
I'm not that familiar with handling dependencies in C#. Does anyone know how to do this correctly?

**Comment by FactEngineCommunity** [comment]
Hi @Blubberblub , do you have all four of these in your path:
kuzu_shared.dll
KuzuDB.dll
kuzunet.dll
libkuzu.lib

**Comment by Blubberblub** [comment]
Hey Victor, thanks for the suggestions. In my case i messed up the build configs in the Visual Studio project. The build lib and project using it should have the same architecture.

**Comment by FactEngineCommunity** [comment]
Hey Blubberblub, all good. So we can close this issue?
I'm just thinking about libKuzu.lib, from memory @NCirit may have generated that file rather than the Kuzu team. Either way, if you are up and running we'll close this issue and move on. Please feel free to share any insights on the make process to put in the doco. Kind regards, Victor

**Comment by FactEngineCommunity** [comment]
Sorry, you did close this. Blubberblub, sing out if you want a copy of Boston to use over Kuzu: https://www.factengine.ai/index.php/products/boston-professional

Here's a video of the sort of thing you can do: https://youtu.be/6E0MshgrUE0?si=tMuAqSvGHkJ21cgE
The video is over SQLite (treating it like a graph database), but you can do the same sort of thing with Kuzu.

If you need to visualise the model or do natural language queries over your model Boston/FactEngine may be the go.
I'm easy to find, my email is in my profile here.
Have a great day, Victor
